from __future__ import annotations

from collections.abc import Callable
from contextlib import AbstractContextManager
from typing import Protocol

from starlette.requests import Request
from starlette.responses import Response

from .models import AuthorizationContext, Client, Code, Decision, Grant, PendingConsent, Subject


class Identity(Protocol):
    async def authenticate(self, request: Request) -> Subject | Response:
        """Return the browser's subject or a host-owned login/error response."""
        ...

    def get_subject(self, subject_id: str) -> Subject | None:
        """Fresh authoritative lookup in a worker thread within a transaction."""
        ...


class Consent(Protocol):
    async def render(
        self, request: Request, context: AuthorizationContext, consent_token: str
    ) -> Response:
        """Render explicit allow/deny POST; include consent_token as a hidden field."""
        ...

    async def decide(self, request: Request, context: AuthorizationContext) -> Decision:
        """Only called after one-use browser-bound consent token validation."""
        ...


class UnitOfWork(Protocol):
    def get_client(self, client_id: str) -> Client | None: ...
    def put_client(self, client: Client) -> None: ...
    def clients(self) -> list[Client]: ...
    def delete_client(self, client_id: str) -> None: ...
    def get_code(self, digest: str) -> Code | None: ...
    def put_code(self, code: Code) -> None: ...
    def delete_code(self, digest: str) -> None: ...
    def codes(self) -> list[Code]: ...
    def get_pending(self, digest: str) -> PendingConsent | None: ...
    def put_pending(self, pending: PendingConsent) -> None: ...
    def delete_pending(self, digest: str) -> None: ...
    def pending(self) -> list[PendingConsent]: ...
    def get_grant(self, family_id: str) -> Grant | None: ...
    def put_grant(self, grant: Grant) -> None: ...
    def grants(self) -> list[Grant]: ...
    def find_token(self, digest: str, kind: str) -> Grant | None: ...
    def prune(self, now: float, client_ttl: int) -> None: ...


class Storage(Protocol):
    def transaction(self) -> AbstractContextManager[UnitOfWork]:
        """Serializable: commit on normal return, rollback on every exception."""
        ...


RegistrationHook = Callable[[Request], None]
RedirectPolicy = Callable[[str], bool]
